### ISSUE TITLE
seen-1 fails with array index out of bounds

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-alyalyaly123#3]
details:

> root@c1296dd783b6:/depsolver/to-test# ./solve ../tests/seen-1/repository.json ../tests/seen-1/initial.json ../tests/seen-1/constraints.json 
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
> 	at depsolver.Main.splitString(Main.java:547)
> 	at depsolver.Main.dependancyBuilder(Main.java:200)
> 	at depsolver.Main.checkInitial(Main.java:119)
> 	at depsolver.Main.main(Main.java:93)
>

**Comment by rgrig** [comment]
Same for seen-6 and seen-9.
